name: pdi_dost
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  intl: ^0.20.2
  shimmer: ^3.0.0
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5
  animate_do: ^3.3.4
  image_picker: ^1.2.1
  http: ^1.6.0
  dartz: ^0.10.1
  connectivity_plus: ^7.0.0
  flutter_screenutil: ^5.9.0
  pinput: ^6.0.2
  get: ^4.7.3
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  package_info_plus: ^9.0.0
  loading_animation_widget: ^1.3.0
  share_plus: ^12.0.1
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/archivo/archivo-thin.ttf
          weight: 100
        - asset: assets/fonts/archivo/archivo-extra-light.ttf
          weight: 200
        - asset: assets/fonts/archivo/archivo-light.ttf
          weight: 300
        - asset: assets/fonts/archivo/archivo-regular.ttf
          weight: 400
        - asset: assets/fonts/archivo/archivo-medium.ttf
          weight: 500
        - asset: assets/fonts/archivo/archivo-semi-bold.ttf
          weight: 600
        - asset: assets/fonts/archivo/archivo-bold.ttf
          weight: 700
        - asset: assets/fonts/archivo/archivo-extra-bold.ttf
          weight: 800
        - asset: assets/fonts/archivo/archivo-black.ttf
          weight: 900

    - family: Geist
      fonts:
        - asset: assets/fonts/geist/geist-thin.ttf
          weight: 100
        - asset: assets/fonts/geist/geist-extra-light.ttf
          weight: 200
        - asset: assets/fonts/geist/geist-light.ttf
          weight: 300
        - asset: assets/fonts/geist/geist-regular.ttf
          weight: 400
        - asset: assets/fonts/geist/geist-medium.ttf
          weight: 500
        - asset: assets/fonts/geist/geist-semi-bold.ttf
          weight: 600
        - asset: assets/fonts/geist/geist-bold.ttf
          weight: 700
        - asset: assets/fonts/geist/geist-extra-bold.ttf
          weight: 800
        - asset: assets/fonts/geist/geist-black.ttf
          weight: 900
